fail_fast: false
repos:
  - repo: https://github.com/razgino11/oxe-pre-commit-hooks.git
    rev: master
    hooks:
      - id: cppcheck
        args: [--addon=dev/cppcheck_naming.json]
      - id: clang-format
        args: [--style=Google]